-- Supabase Schema Setup for Planogram AI Engine

-- Create the main compliance_logs table
CREATE TABLE compliance_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    planogram_id TEXT NOT NULL,
    store_id TEXT NOT NULL,
    status TEXT NOT NULL, -- 'pass', 'fail', or 'error'
    compliance_score INTEGER NOT NULL,
    issues JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of missing/misplaced/unexpected products
    correct JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of correct placement strings
    summary TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: The Python backend automatically populates these fields based on the Pydantic JSON schema generated by Gemini.
