"""
3_train.py
----------
STEP 3 — Train a custom YOLOv8 model on FamilyMart shelf products.

Prerequisites:
  - Labeled images in yolo_test/training_data/images/train/ and val/
  - Label files in yolo_test/training_data/labels/train/ and val/
  - dataset.yaml generated by 2_label_guide.py

Run:
    python yolo_test/3_train.py

    Optional flags:
    --epochs 50       (default: 50, use 100+ for better accuracy)
    --model yolov8s   (nano=fastest, small=balanced, medium=most accurate)
    --imgsz 640       (image size, default 640)

Output:
    yolo_test/results/train/   ← trained model weights + metrics
    yolo_test/results/train/weights/best.pt  ← USE THIS for detection
"""

import argparse
import sys
from pathlib import Path

try:
    from ultralytics import YOLO
except ImportError:
    print("[ERROR] Run: pip install ultralytics")
    sys.exit(1)


DATASET_YAML = Path("yolo_test/training_data/dataset.yaml")
RESULTS_DIR  = Path("yolo_test/results/train")

# Model size options — tradeoff between speed and accuracy
MODEL_OPTIONS = {
    "yolov8n": "Nano   — fastest, least accurate  (~3MB)  good for testing",
    "yolov8s": "Small  — balanced speed/accuracy  (~11MB) recommended start",
    "yolov8m": "Medium — more accurate, slower     (~25MB) for production",
    "yolov8l": "Large  — high accuracy, needs GPU  (~44MB)",
    "yolov8x": "XLarge — most accurate, slow       (~68MB)",
}


def check_training_data():
    """Verify training data exists before starting."""
    train_images = list(Path("yolo_test/training_data/images/train").glob("*.jpg")) + \
                   list(Path("yolo_test/training_data/images/train").glob("*.png"))
    val_images   = list(Path("yolo_test/training_data/images/val").glob("*.jpg")) + \
                   list(Path("yolo_test/training_data/images/val").glob("*.png"))

    print(f"[train] Training images : {len(train_images)}")
    print(f"[train] Validation images: {len(val_images)}")

    if len(train_images) == 0:
        print("\n[ERROR] No training images found.")
        print("        Add labeled images to: yolo_test/training_data/images/train/")
        print("        Add label files to:    yolo_test/training_data/labels/train/")
        print("        Then run 2_label_guide.py for instructions.")
        return False

    if len(train_images) < 20:
        print(f"\n[WARNING] Only {len(train_images)} training images found.")
        print("          Minimum 50–100 recommended for useful results.")
        print("          Proceeding anyway — accuracy may be poor.")

    if not DATASET_YAML.exists():
        print(f"\n[ERROR] dataset.yaml not found. Run: python yolo_test/2_label_guide.py")
        return False

    return True


def train(model_name: str, epochs: int, imgsz: int):
    print(f"\n{'='*60}")
    print("  YOLOv8 Custom Training — FamilyMart Planogram")
    print(f"{'='*60}")
    print(f"  Model  : {model_name}  ({MODEL_OPTIONS.get(model_name, '')})")
    print(f"  Epochs : {epochs}")
    print(f"  Img sz : {imgsz}px")
    print(f"  Data   : {DATASET_YAML}")
    print(f"{'='*60}\n")

    if not check_training_data():
        sys.exit(1)

    # Start from pre-trained weights (transfer learning — much faster)
    model = YOLO(f"{model_name}.pt")

    print(f"[train] Starting training for {epochs} epochs...\n")
    results = model.train(
        data=str(DATASET_YAML),
        epochs=epochs,
        imgsz=imgsz,
        batch=8,             # reduce to 4 if you run out of memory
        patience=15,         # stop early if no improvement for 15 epochs
        save=True,
        project=str(RESULTS_DIR.parent),
        name="train",
        exist_ok=True,
        pretrained=True,     # transfer learning from COCO weights
        optimizer="AdamW",
        lr0=0.001,
        weight_decay=0.0005,
        plots=True,          # generate training plots
        verbose=True,
    )

    best_weights = RESULTS_DIR / "weights" / "best.pt"
    print(f"\n{'='*60}")
    print("  Training Complete!")
    print(f"  Best model: {best_weights}")
    print(f"  mAP50: {results.results_dict.get('metrics/mAP50(B)', 'N/A'):.3f}")
    print(f"\n  NEXT STEP: Test your trained model:")
    print(f"  python yolo_test/4_test_trained.py --photo <shelf_photo>")
    print(f"{'='*60}\n")

    return str(best_weights)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model", default="yolov8s",
        choices=list(MODEL_OPTIONS.keys()),
        help="Model size (default: yolov8s)"
    )
    parser.add_argument("--epochs", type=int, default=50, help="Training epochs (default: 50)")
    parser.add_argument("--imgsz",  type=int, default=640, help="Image size (default: 640)")
    args = parser.parse_args()

    print("\nAvailable model sizes:")
    for name, desc in MODEL_OPTIONS.items():
        marker = "→" if name == args.model else " "
        print(f"  {marker} {name}: {desc}")

    train(args.model, args.epochs, args.imgsz)
